language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py makemigrations core"
  - docker-compose run app sh -c "python manage.py migrate"
  - docker-compose run app sh -c "python manage.py test"
